# Imports

In [1]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)

# Database Connection

In [3]:
SERVER = "localhost"
DATABASE = "olistDW"

connection_string = (
    f"mssql+pyodbc://@{SERVER}/{DATABASE}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

engine = create_engine(connection_string)

print("Connected Successfully")

Connected Successfully

# If use password in your sql, you should use this code

In [15]:
'''SERVER = "localhost"
DATABASE = "SalesDW"
USERNAME = "sa"
PASSWORD = "your_password"

connection_string = (
    f"mssql+pyodbc://{USERNAME}:{PASSWORD}"
    f"@{SERVER}/{DATABASE}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)

engine = create_engine(connection_string)'''

'SERVER = "localhost"\nDATABASE = "SalesDW"\nUSERNAME = "sa"\nPASSWORD = "your_password"\n\nconnection_string = (\n    f"mssql+pyodbc://{USERNAME}:{PASSWORD}"\n    f"@{SERVER}/{DATABASE}"\n    "?driver=ODBC+Driver+17+for+SQL+Server"\n)\n\nengine = create_engine(connection_string)'

# Test Connection

In [4]:
query = """
SELECT TOP 5 *
FROM Fact_Sales
"""

df_test = pd.read_sql(query, engine)

df_test.head()

,sales_key,order_id,customer_id,product_id,seller_id,order_date,payment_value,freight_value,quantity
0,1,0005a1a1728c9d785b8e2b08b904576c,16150771dfd4776261284213b89c304e,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-19,157.60,11.65,1
1,2,0005f50442cb953dcd1d21e1fb923495,351d3cb2cee3c7fd0af6616c82df21d3,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-02,65.39,11.40,1
2,3,000f25f4d72195062c040b12dce9a18a,86ade8ebc14f18dd6c3ea75bd0eb7534,1c05e0964302b6cf68ca0d15f326c6ba,7c67e1448b00f6e969d365cea6b010ab,2018-03-07,164.39,44.40,1
3,4,0010b2e5201cc5f1ae7e9c6cc8f5bd00,57ef317d4818cb42680fc9dfd13867ce,5a419dbf24a8c9718fe522b81c69f61a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-09-11,65.50,16.60,1
4,5,00119ff934e539cf26f92b9ef0cdfed8,7dd2e283f47deac853cf70f3b63c8d86,21b1c2f67a9aafb5af0eb06c13b9dbda,c864036feaab8c1659f65ea4faebe1da,2017-08-06,236.88,16.98,1

# Function to Load SQL Files

In [5]:
def load_sql_query(file_path):

    with open(file_path, "r", encoding="utf-8") as file:
        sql = file.read()

    return sql

# Load Main EDA Dataset

In [8]:
sql = load_sql_query(
    "../database/EDA/01_sales_dataset.sql"
)

sales_df = pd.read_sql(sql, engine)

sales_df.head()

,sales_key,order_id,quantity,payment_value,freight_value,customer_id,customer_city,customer_state,seller_id,seller_city,seller_state,product_id,category,weight,date,year,quarter,month,month_name,week,day_name
0,1,0005a1a1728c9d785b8e2b08b904576c,1,157.60,11.65,16150771dfd4776261284213b89c304e,santos,SP,a416b6a846a11724393025641d4edd5e,sao paulo,SP,310ae3c140ff94b03219ad0adc3c778f,beleza_saude,2000.00,2018-03-19,2018,1,3,March,12,Monday
1,2,0005f50442cb953dcd1d21e1fb923495,1,65.39,11.40,351d3cb2cee3c7fd0af6616c82df21d3,jandira,SP,ba143b05f0110f0dc71ad71b4466ce92,sao paulo,SP,4535b0e1091c278dfd193e5a1d63b39f,livros_tecnicos,850.00,2018-07-02,2018,3,7,July,27,Monday
2,3,000f25f4d72195062c040b12dce9a18a,1,164.39,44.40,86ade8ebc14f18dd6c3ea75bd0eb7534,volta redonda,RJ,7c67e1448b00f6e969d365cea6b010ab,itaquaquecetuba,SP,1c05e0964302b6cf68ca0d15f326c6ba,moveis_escritorio,9375.00,2018-03-07,2018,1,3,March,10,Wednesday
3,4,0010b2e5201cc5f1ae7e9c6cc8f5bd00,1,65.50,16.60,57ef317d4818cb42680fc9dfd13867ce,rio de janeiro,RJ,3504c0cb71d7fa48d967e0e4c94d59d9,maua,SP,5a419dbf24a8c9718fe522b81c69f61a,cool_stuff,1800.00,2017-09-11,2017,3,9,September,37,Monday
4,5,00119ff934e539cf26f92b9ef0cdfed8,1,236.88,16.98,7dd2e283f47deac853cf70f3b63c8d86,nova iguacu,RJ,c864036feaab8c1659f65ea4faebe1da,campo largo,PR,21b1c2f67a9aafb5af0eb06c13b9dbda,esporte_lazer,9800.00,2017-08-06,2017,3,8,August,32,Sunday

# Basic Data Inspection

In [9]:
sales_df.shape

(230248, 21)

In [10]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230248 entries, 0 to 230247
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   sales_key       230248 non-null  int64
 1   order_id        230248 non-null  object
 2   quantity        230248 non-null  int64
 3   payment_value   230248 non-null  float64
 4   freight_value   230248 non-null  float64
 5   customer_id     230248 non-null  object
 6   customer_city   230248 non-null  object
 7   customer_state  230248 non-null  object
 8   seller_id       230248 non-null  object
 9   seller_city     230248 non-null  object
 10  seller_state    230248 non-null  object
 11  product_id      230248 non-null  object
 12  category        226947 non-null  object
 13  weight          230210 non-null  float64
 14  date            230248 non-null  object
 15  year            230248 non-null  int64
 16  quarter         230248 non-null  int64
 17  month           230248 non-null  int64
 18  month_name      230248 non-null  object
 19  week            230248 non-null  int64
 20  day_name        230248 non-null  object
dtypes: float64(3), int64(6), object(12)
memory usage: 36.9+ MB

In [11]:
sales_df.describe()

,sales_key,quantity,payment_value,freight_value,weight,year,quarter,month,week
count,230248.00,230248.00,230248.00,230248.00,230210.00,230248.00,230248.00,230248.00,230248.00
mean,115124.50,1.20,176.40,20.02,2104.23,2017.54,2.35,6.03,24.46
std,66467.02,0.70,270.20,15.83,3770.67,0.50,1.06,3.23,14.06
min,1.00,1.00,0.00,0.00,0.00,2016.00,1.00,1.00,1.00
25%,57562.75,1.00,63.29,13.08,300.00,2017.00,1.00,3.00,13.00
50%,115124.50,1.00,111.64,16.28,700.00,2018.00,2.00,6.00,24.00
75%,172686.25,1.00,192.50,21.18,1800.00,2018.00,3.00,8.00,34.00
max,230248.00,21.00,13664.08,409.68,40425.00,2018.00,4.00,12.00,53.00

# Missing Values Analysis

In [12]:
missing = sales_df.isnull().sum()

missing[missing > 0].sort_values(ascending=False)

category    3301
weight        38
dtype: int64

# Monthly Sales Dataset

In [14]:
monthly_sql = load_sql_query(
    "../database/EDA/03_monthly_sales_trend.sql"
)

monthly_sales = pd.read_sql(
    monthly_sql,
    engine
)

monthly_sales.head()

   year  month month_name  total_sales  total_quantity
0  2016      9  September       695.04               8
1  2016     10    October    147829.16             932
2  2016     12   December        39.24               2
3  2017      1    January    375558.82            2687
4  2017      2   February    688269.58            4625

# Top Customers Dataset

In [15]:
customer_sql = load_sql_query(
    "../database/EDA/05_top_customers.sql"
)

top_customers = pd.read_sql(
    customer_sql,
    engine
)

top_customers.head()

,customer_id,city,state,total_spent,total_orders
0,1617b1357756262bfa56ab541c47bc16,rio de janeiro,RJ,218625.28,1
1,bd5d39761aa56689a265d95d8d32b8be,goiania,GO,90512.00,1
2,be1b70680b9f9694d8c70f41fa3dc92b,sao paulo,SP,88096.00,1
3,05455dfa7cd02f13d132aa7a6a9729c6,divinopolis,MG,72978.48,1
4,1ff773612ab8934db89fd5afa8afe506,rio de janeiro,RJ,60372.00,1

# Customer Segmentation Dataset

In [16]:
rfm_sql = load_sql_query(
    "../database/EDA/11_customer_segmentation.sql"
)

rfm_df = pd.read_sql(
    rfm_sql,
    engine
)

rfm_df.head()

,customer_id,frequency,monetary,last_purchase_date,recency_days
0,1617b1357756262bfa56ab541c47bc16,1,218625.28,2017-09-29,383
1,bd5d39761aa56689a265d95d8d32b8be,1,90512.00,2017-08-23,420
2,be1b70680b9f9694d8c70f41fa3dc92b,1,88096.00,2018-02-22,237
3,05455dfa7cd02f13d132aa7a6a9729c6,1,72978.48,2017-11-24,327
4,1ff773612ab8934db89fd5afa8afe506,1,60372.00,2018-04-19,181

# KPI Dataset

In [17]:
kpi_sql = load_sql_query(
    "../database/EDA/12_sales_kpi_dashboard.sql"
)

kpi_df = pd.read_sql(
    kpi_sql,
    engine
)

kpi_df

,total_orders,total_customers,total_sellers,total_products,total_revenue,total_quantity_sold,avg_order_value,avg_freight_cost
0,98665,98665,3095,32951,40616269.42,275569,176.40,20.02

# Revenue Overview

In [18]:
sales_df["payment_value"].agg(
    ["count", "sum", "mean", "min", "max"]
)

count     230248.00
sum     40616269.42
mean         176.40
min            0.00
max        13664.08
Name: payment_value, dtype: float64

# Top Categories

In [19]:
(
    sales_df
    .groupby("category")["payment_value"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

category
cama_mesa_banho          3425107.34
beleza_saude             3314746.24
informatica_acessorios   3170660.90
moveis_decoracao         2860352.78
relogios_presentes       2858433.36
esporte_lazer            2784255.12
utilidades_domesticas    2189516.26
automotivo               1704588.66
ferramentas_jardim       1676561.50
cool_stuff               1559396.00
Name: payment_value, dtype: float64

# Top States

In [20]:
(
    sales_df
    .groupby("customer_state")["payment_value"]
    .sum()
    .sort_values(ascending=False)
)

customer_state
SP   15194419.32
RJ    5538694.88
MG    4652303.28
RS    2294554.00
PR    2129207.98
BA    1594820.72
SC    1572687.42
GO    1027758.00
DF     865247.46
ES     811610.68
PE     752754.54
CE     687695.66
PA     523576.70
MT     513609.24
MA     397132.54
PB     361968.38
MS     328674.56
PI     273559.92
RN     232529.80
AL     222568.84
SE     176875.02
TO     144562.34
RO     131772.00
AM      69506.60
AC      49969.72
AP      43285.40
RR      24924.42
Name: payment_value, dtype: float64

# Save Processed Dataset

In [21]:
sales_df.to_csv(
    "../data/processed/sales_dataset.csv",
    index=False
)